name: Rust

on:
  push:
    tags:
      - '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release --target x86_64-unknown-linux-gnu
    - name: Strip Binary
      run: strip "target/x86_64-unknown-linux-gnu/release/ruast_qqbot"
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: binary
        path: "target/x86_64-unknown-linux-gnu/release/ruast_qqbot"
  release:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v4
      with:
        name: binary
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: ruast_qqbot
